#+title: Home-manager configuration
#+author: Atri Hegde
#+auto_tangle: t
#+property: header-args :tangle home.nix

* TOC :TOC:
- [[#preface][Preface]]
  - [[#todo][TODO]]
- [[#user-setup][User setup]]
- [[#environment-variables][Environment variables]]
- [[#packages][Packages]]
- [[#programs-and-services][Programs and Services]]
  - [[#shell][Shell]]
  - [[#terminal-emulator][Terminal Emulator]]
  - [[#multimedia][Multimedia]]
- [[#theme-settings][Theme settings]]
  - [[#cursor][Cursor]]
  - [[#gtk][GTK]]
- [[#end][End]]

* Preface
** TODO
#+begin_src nix
{config, pkgs, ...}:
{
  home.stateVersion = "23.05";
  programs.home-manager.enable = true;
#+end_src

* User setup
#+begin_src nix
  home.username = "mizuuu";
  home.homeDirectory = "/home/mizuuu";
#+end_src

* Environment variables
#+begin_src nix
  home = {
    sessionVariables = {
      MOZ_ENABLE_WAYLAND = 1;
      SDL_VIDEODRIVER = "wayland";
      QT_QPA_PLATFORM = "wayland";
      GDK_BACKEND = "wayland,x11";
      _JAVA_AWT_WM_NONREPARENTING = 1;
      _JAVA_OPTIONS = "-Dawt.useSystemAAFontSettings=on";
      # only needed for Sway
      XDG_CURRENT_DESKTOP = "sway";
    };
  };
#+end_src

* Packages
#+begin_src nix
  home.packages = with pkgs; [
    firefox
    pfetch
    carapace
    btop
    discord
    sqlite
    glib
    neofetch
    android-studio
    swappy
    grim
    sway-contrib.grimshot
    cmake
    ledger
    libgccjit
    llvmPackages_rocm.clang
    yt-dlp
    alsa-utils
    obs-studio
    wl-clipboard
    swaylock
    wayland-protocols
    gotests
    git
    _7zz
    neovim
    ripgrep
    fd
    brightnessctl
    slurp
    gnumake
    # (ncmpcpp.override { visualizerSupport = true; })
    mpc-cli
    playerctl
    ## Dev languages
    # Golang
    go
    gopls
    gore
    gotools
    # Rust
    rustup
    # Node
    nodejs_20
    # Python
    python3
    joshuto
    # Fonts
  ];
#+end_src

* Programs and Services
** Shell
*** Nushell
I primarily use NuShell due to its snappiness.

Configuration file must be copied over from the ~config~ folder.

I have included it in home packages since config files conflict otherwise.

| Shell   | Time taken (10 launches) |
|---------+--------------------------|
| NuShell | ~0.01s                   |
| Bash    | ~0.13s                   |
| ZSH     | ~0.65s                   |

*** Zoxide and Direnv
Zoxide is a smarter better ~cd~.
Direnv helps me with my dev environments.

#+begin_src nix
  programs.zoxide = {
    enable = true;
    package = pkgs.zoxide;
    enableNushellIntegration = true;
  };

  programs.direnv = {
    enable = true;
    enableBashIntegration = true;
    enableNushellIntegration = true;
  };
#+end_src

** Terminal Emulator
#+begin_src nix
  programs.foot = {
    enable = true;
    package = pkgs.foot;
    server.enable = true;
    settings = {
      main = {
        app-id = "foot";
        title = "foot";
        font = "JetBrainsMono Nerd Font:size=8";
        dpi-aware = "yes";
        pad = "10x10 center";
      };
      cursor = {
        style = "beam";
        blink = "yes";
      };
      colors = {
        alpha = "0.9";
        background = "14151b";
        foreground = "f8f8f2";
        regular0 = "21222c";
        regular1 = "ff5555";
        regular2 = "50fa7b";
        regular3 = "f1fa8c";
        regular4 = "bd93f9";
        regular5 = "ff79c6";
        regular6 = "8be9fd";
        regular7 = "f8f8f2";
        bright0 = "6272a4";
        bright1 = "ff6e6e";
        bright2 = "69ff94";
        bright3 = "ffffa5";
        bright4 = "d6acff";
        bright5 = "ff92df";
        bright6 = "a4ffff";
        bright7 = "ffffff";
        selection-foreground="ffffff";
        selection-background="44475a";
        urls = "8be9fd";
      };
    };
  };
#+end_src

*** Starship and Exa
Starship gives me a fancy prompt.
Exa gives me a icons and a better experience with ~ls~.
#+begin_src nix
  programs.starship = {
    enable = true;
    package = pkgs.starship;
    enableBashIntegration = true;
    enableNushellIntegration = true;
  };

  programs.exa = {
    enable = true;
    package = pkgs.exa;
    enableAliases = true;
    icons = true;
  };
#+end_src

** Multimedia
*** MPV
#+begin_src nix
programs.mpv = {
  enable = true;
  package = pkgs.wrapMpv (pkgs.mpv-unwrapped.override { vapoursynthSupport = true; }) { youtubeSupport = true; };
  config = {
    profile = "gpu-hq";
    force-window = true;
    ytdl-format = "bestvideo+bestaudio";
    cache-default = 4000000;
  };
};
#+end_src

*** MPD
#+begin_src nix
  services.mpd = {
    enable = true;
    package = pkgs.mpd;
    extraConfig = ''
      db_file "~/Music/tag_cache"
      log_file "syslog"
      music_directory "~/Music/music"
      playlist_directory "~/Music/playlists"
      pid_file "~/Music/pid"
      state_file "~/Music/state"
      sticker_file "~/Music/sticker.sql"

      audio_output {
        type            "pipewire"
        name            "PipeWire Sound Server"
      }

      audio_output {
        type                    "fifo"
        name                    "my_fifo"
        path                    "/tmp/mpd.fifo"
        format                  "44100:16:2"
      }
      '';
    # dataDir = "~/Music";
    # dbFile = "~/Music/tag_cache";
    musicDirectory = "~/Music/music";
    # playlistDirectory = "~/Music/playlists";
  };
#+end_src

**** Discord RPC for MPD
#+begin_src nix
  services.mpd-discord-rpc = {
    enable = true;
    package = pkgs.mpd-discord-rpc;
    settings = {
      id = 677226551607033903;
      hosts = ["localhost:6600"];
      format = {
        details = "$title";
        state = "$artist / $album";
      };
    };
  };
#+end_src


*** NCMPCPP
#+begin_src nix
  programs.ncmpcpp = {
    enable = true;
    package = (pkgs.ncmpcpp.override {visualizerSupport = true;});
    mpdMusicDir = "~/Music/music";
  };
#+end_src

* Theme settings
** Cursor
#+begin_src nix
  home.pointerCursor = {
    name = "Capitaine Cursors";
    package = pkgs.capitaine-cursors;
    gtk.enable = true;
  };
#+end_src

** GTK
#+begin_src nix
  gtk = {
    enable = true;
    cursorTheme = {
      name = "Capitaine Cursors";
      package = pkgs.capitaine-cursors;
    };
    theme = {
      name = "Materia-dark";
      package = pkgs.materia-theme;
    };
    iconTheme = {
      name = "Papirus-Dark";
      package = pkgs.papirus-icon-theme;
    };
    gtk3.extraConfig = {
      Settings = ''
        gtk-application-prefer-dark-theme=1
      '';
    };
    gtk4.extraConfig = {
      Settings = ''
        gtk-application-prefer-dark-theme=1
      '';
    };
  };
#+end_src

* End
#+begin_src nix
}
#+end_src
